name: ParkourGame
version: 1.0
authors: ['aojiangQAQ（鳌江）', 'SGly']
main: com.sgly.aojiang.parkourgame.ParkourGame
api-version: 1.16
commands:
  pk:
    description: Primary command for managing parkour courses
    usage: /pk <command>
    aliases: [parkour]
